#!/usr/bin/env bash
#
# generate-credentials.sh
# -----------------------
# Generate strong credentials for PANDAI production/local use.
#
# The script NEVER prints the generated secret values. By default it writes
# only to `.env.local` (which is gitignored) with mode 600.
#
# Usage:
#   ./scripts/generate-credentials.sh                 # write .env.local (refuse if exists)
#   ./scripts/generate-credentials.sh --force         # write/overwrite .env.local after backing up
#   ./scripts/generate-credentials.sh --show          # only for an interactive terminal; prints values
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

TARGET="${1:-}"
FORCE=0
SHOW=0

case "${TARGET}" in
  --force) FORCE=1 ;;
  --show)  SHOW=1 ;;
  *)
    if [[ -n "${TARGET}" ]]; then
      echo "Unknown option: ${TARGET}" >&2
      echo "Usage: $0 [--force] [--show]" >&2
      exit 2
    fi
    ;;
esac

random_hex() {
  local bytes="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${bytes}"
  else
    # Portable fallback if openssl is unavailable.
    head -c "${bytes}" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# Validate that we have 32+ random hex bytes (64 hex chars).
JWT_SECRET="$(random_hex 32)"
PASSWORD_SALT="$(random_hex 32)"

if [[ ${#JWT_SECRET} -ne 64 || ${#PASSWORD_SALT} -ne 64 ]]; then
  echo "ERROR: Failed to generate secure random values." >&2
  exit 1
fi

if [[ -f "${REPO_ROOT}/.env.local" && ${FORCE} -eq 0 ]]; then
  echo "ERROR: ${REPO_ROOT}/.env.local already exists." >&2
  echo "Use --force to overwrite (a timestamped backup will be created first)." >&2
  exit 1
fi

if [[ -f "${REPO_ROOT}/.env.local" ]]; then
  backup="${REPO_ROOT}/.env.local.$(date +%Y%m%d%H%M%S).bak"
  cp "${REPO_ROOT}/.env.local" "${backup}"
  chmod 600 "${backup}"
  echo "Backup of previous .env.local stored at: ${backup}"
fi

# Write the credentials to a gitignored local file. This intentionally avoids
# printing the values to stdout/logs so they cannot leak into command history.
cat > "${REPO_ROOT}/.env.local" <<EOF
# Generated by scripts/generate-credentials.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT THIS FILE.
JWT_SECRET=${JWT_SECRET}
PASSWORD_SALT=${PASSWORD_SALT}
EOF

chmod 600 "${REPO_ROOT}/.env.local"

echo
echo "Credentials generated successfully."
echo "File: .env.local (mode 600, gitignored)"
echo
echo "Next steps:"
echo "  1. Copy/merge the values into your hosting provider's environment variables."
echo "  2. Rotate the same values in Neon (DATABASE_URL password) and Vercel."
echo "  3. Start the app with: source .env.local && bun run dev"
echo
echo "Credentials are intentionally NOT printed here for security."

if [[ ${SHOW} -eq 1 ]]; then
  if [[ ! -t 1 ]]; then
    echo "WARNING: --show used in non-interactive mode; values are still hidden." >&2
    exit 1
  fi
  echo
  echo "=== .env.local (for manual copy only) ==="
  echo "JWT_SECRET=${JWT_SECRET}"
  echo "PASSWORD_SALT=${PASSWORD_SALT}"
  echo "========================================="
fi
